poll4dates/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("polls.urls"))
]

polls/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'polls'

urlpatterns = [
    path("", TemplateView.as_view(template_name='polls/index.html'), name='index'),
    path("plan/", views.PollCreate.as_view(), name='plan'),
    path("polls/", views.PollList.as_view(), name='my_polls'),
    path("polls/<uuid:guid>/", views.PollDetail.as_view(), name='poll_detail'),
    path("polls/<uuid:guid>/edit/", views.PollUpdate.as_view(), name='poll_update'),
    path("polls/<uuid:guid>/delete/", views.PollDelete.as_view(), name='delete'),
    path("polls/<uuid:guid>/invite/", views.invite, name='invite'),
    path("polls/<uuid:guid>/guests/", views.add_guest, name='add_guest'),
    path("polls/<uuid:poll_guid>/guests/<uuid:guest_guid>/", views.get_guest, name='get_guest'),
    path("guests/<uuid:guid>/edit/", views.edit_guest_name, name="edit_guest_name"),
    path("contact/", views.contact, name='contact')
]

polls/models.py
from django.db import models
from django.utils import timezone
import string
import secrets 
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django_celery_beat.models import ClockedSchedule, PeriodicTask
from django.db.models.constraints import UniqueConstraint
from datetime import datetime, timedelta
from django.db import transaction
import pytz
from django.urls import reverse
import uuid


def generate_token(length):
    alphabet = string.ascii_letters + string.digits
    return ''.join([secrets.choice(alphabet) for i in range(length)])


def str_to_date(string):
    return datetime.strptime(string, '%Y-%m-%dT%H:%M')


class Poll(models.Model):
    guid = models.UUIDField(default=uuid.uuid1, db_index=True) 
    creator = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='polls')
    event_name = models.CharField(max_length=225)
    event_organizer = models.CharField(max_length=225)
    event_location = models.CharField(max_length=225, blank=True, null=True)
    event_details = models.CharField(max_length=350, blank=True, null=True)
    event_timezone = models.CharField(max_length=225)
    rsvp_by = models.DateTimeField()
    token = models.CharField(max_length=8, default=generate_token(8))

    def __str__(self):
        return self.event_name


    def get_absolute_url(self):
        return reverse("polls:poll_detail", kwargs={"pk": self.pk})
    
    
    @property
    def ended(self):
        if isinstance(self.rsvp_by, str):
            return str_to_date(self.rsvp_by) < datetime.now()
        return self.rsvp_by < timezone.now()
    
    @property
    def max_vote(self):
        return self.time_slots.annotate(votes_count=models.Count('votes'))\
            .aggregate(max_vote=models.Max('votes_count'))['max_vote']
    
    @property
    def guests_voted(self):
        return self.guests.filter(votes__isnull=False).distinct()
    
    @property
    def guests_waiting(self):
        return self.guests.filter(votes__isnull=True)


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        rsvp_by = None

        if isinstance(self.rsvp_by, str):
            rsvp_by = str_to_date(self.rsvp_by)

        else:
            desired_tz = pytz.timezone("Africa/Cairo")
            rsvp_by = self.rsvp_by.astimezone(desired_tz)


        task_found = PeriodicTask.objects.filter(name__contains=self.pk).exists()
        
        with transaction.atomic() :
            if task_found:
                task = PeriodicTask.objects.get(name__contains=self.pk)
                
                desired_tz = pytz.timezone("Africa/Cairo")
                converted_time = task.clocked.clocked_time.astimezone(desired_tz)
                t1 = converted_time.strftime("%Y-%m-%dT%H:%M")
                
                rsvp_plus = rsvp_by + timedelta(minutes=2)
                t2 = rsvp_plus.strftime("%Y-%m-%dT%H:%M")
                
                if t1 != t2:
                    task.clocked.delete()
                    task.delete()

                    clocked_schedule = ClockedSchedule.objects.create(clocked_time=rsvp_by + timedelta(minutes=2))

                    PeriodicTask.objects.create(
                        clocked=clocked_schedule,
                        name=f'Send result email to poll {self.id} creator and guests',
                        task='polls.tasks.fetch_result_and_send_email',
                        args=[self.id],
                        one_off=True
                    )
            else:
                clocked_schedule = ClockedSchedule.objects.create(clocked_time=rsvp_by + timedelta(minutes=2))

                PeriodicTask.objects.create(
                    clocked=clocked_schedule,
                    name=f'Send result email to poll {self.id} creator and guests',
                    task='polls.tasks.fetch_result_and_send_email',
                    args=[self.id],
                    one_off=True
                )

class TimeSlot(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='time_slots')
    day = models.DateField()
    start = models.TimeField()
    end = models.TimeField()

    def __str__(self):
        return f'{self.day}@{self.start}-{self.end}'

    @property
    def votes_count(self):
        return self.votes.count()

class Guest(models.Model):
    guid = models.UUIDField(default=uuid.uuid1, db_index=True)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='guests')
    name = models.CharField(max_length=225)
    email = models.EmailField(max_length=250, blank=False, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        constraints = [
            UniqueConstraint("poll", "name", name="unique_name_per_poll"),
            UniqueConstraint("poll", "email", name="unique_email_per_poll")
        ]


class Vote(models.Model):
    time_slot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE, related_name='votes')
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE, related_name='votes')
    

class Message(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE, related_name='messages')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    sender_id = models.BigIntegerField()
    content_sender = GenericForeignKey('content_type', 'sender_id')
    content = models.CharField(max_length=250)
    sent_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['sent_at']

    

polls/forms.py
from typing import Any
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError
from .models import Poll
from datetime import datetime
import ast

class TimeSlotsField(forms.CharField):
    widget = forms.SelectMultiple()

    def clean(self, value: Any) -> Any:
        value = super().clean(value)
        if not value:
            raise ValidationError('This field is required')
        timeslots = []
        value = ast.literal_eval(value)
        for slot in value:
            day, start_time, end_time = slot.split(',')
            start_time = datetime.strptime(start_time, '%H:%M')
            end_time = datetime.strptime(end_time, '%H:%M')
            timeslots.append({'day': day, 'start': start_time, 'end': end_time})
        return timeslots

class PollCreationForm(forms.Form):
    event_name = forms.CharField(max_length=225, label='Name the Event *')
    event_organizer = forms.CharField(max_length=225, label='Event Organizer *')
    event_details = forms.CharField(max_length=350, label='Event details (optional)', required=False)
    event_location = forms.CharField(max_length=225, label='Event location (optional)', required=False)
    event_timezone = forms.CharField(max_length=225, label='Event time zone')
    rsvp_by = forms.DateTimeField(label='RSVP by *')
    timeslots = TimeSlotsField(label='Timeslots')

    def clean_rsvp_by(self):
        rsvp_by = self.cleaned_data.get('rsvp_by')
        if rsvp_by < timezone.now():
            raise ValidationError('Please enter a future date.')
        return rsvp_by

    def save(self, *args, **kwargs):
        data = {k:v for k,v in self.cleaned_data.items() if k != 'timeslots'}
        poll = Poll(**data)
        return poll

polls/views.py
from .models import Poll, Guest
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import FormView
from .forms import PollCreationForm
from django.shortcuts import redirect
from django.urls import reverse_lazy
from datetime import datetime 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives, get_connection
from django.template.loader import render_to_string
from django.conf import settings
from urllib.parse import urlencode
from django.http import JsonResponse
from django.core import serializers
from django.shortcuts import render
from django.contrib import messages
from .tasks import notify_guests_with_changes, invite_guests, send_contact_message


class PollCreate(FormView):
    template_name = 'polls/create.html'
    form_class = PollCreationForm
    login_url = reverse_lazy('account_login')
    
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            request.session['form_data'] = request.POST
            request.session['timeslots'] = request.POST.getlist('timeslots')
            return redirect_to_login(self.request.get_full_path(), self.login_url)
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        poll = form.save()
        poll.creator = self.request.user
        poll.save()
        for slot in form.cleaned_data['timeslots']:
            poll.time_slots.create(**slot)
        
        if 'form_data' in self.request.session: 
            del self.request.session['form_data']
            del self.request.session['timeslots']
       
        success_url = reverse_lazy('polls:poll_detail', kwargs={'guid': poll.guid})
        return redirect(success_url, {'poll': poll})


class PollList(LoginRequiredMixin,  ListView):
    model = Poll
    context_object_name = 'polls'
    template_name='polls/list.html'

    def get_queryset(self):
        current_user = self.request.user
        queryset = Poll.objects.filter(creator=current_user)
        return queryset
    

class PollDetail(DetailView):
    model = Poll
    template_name='polls/show.html'
    context_object_name = 'poll'
    login_url = reverse_lazy('account_login')
    uuid_url_kwarg = 'guid'

    def get_queryset(self):
        current_user = self.request.user
        queryset = Poll.objects.prefetch_related('time_slots')
        if current_user.is_authenticated:
            queryset = queryset.prefetch_related('messages').filter(creator=current_user)
        return queryset
    
    def get(self, request, *args, **kwargs):
        invite = request.GET.get('invite', None)
        gid = request.GET.get('gid', None)

        if not invite and not gid:
            if not request.user.is_authenticated:
                return redirect_to_login(request.get_full_path(), self.login_url)
        
        try:
            poll_guid = self.kwargs[self.uuid_url_kwarg]
            queryset = self.get_queryset()
            poll = queryset.get(guid=poll_guid) if not invite else queryset.get(guid=poll_guid, token=invite)
            return render(request, 'polls/show.html', {'poll': poll})
        except:
            return render(request, '404.html')
        
    
class PollUpdate(LoginRequiredMixin, UpdateView):
    model = Poll
    template_name = "polls/show.html"
    fields = ['event_name', 'event_details', 'event_location', 'rsvp_by']
    uuid_url_kwarg = 'guid'
    
    def get(self, request, *args, **kwargs):
        poll_url = reverse_lazy('polls:poll_detail', kwargs={'guid': self.kwargs[self.uuid_url_kwarg]})
        return redirect(poll_url)

    def post(self, *args, **kwargs):
        post_data = self.request.POST

        if '_method' in post_data and post_data['_method'] == 'put':
            data = {k:v for k,v in post_data.items() if k not in ['csrfmiddlewaretoken', '_method']}
            poll = Poll.objects.get(guid=self.kwargs[self.uuid_url_kwarg])
            success_url = reverse_lazy('polls:poll_detail', kwargs={'guid': poll.guid})

            if poll.ended and 'close' not in data and 'rsvp_by' not in data:
                return redirect(success_url, {'poll': poll})
            
            if 'close' in data:
                poll.rsvp_by = datetime.now().strftime("%Y-%m-%dT%H:%M")
                poll.save()
                if 'notify' in data:
                    notify_guests_with_changes.delay(poll.pk, 'closed')                

            elif 'date' in data:
                poll.time_slots.create(day=data['date'], start=data['start'], end=data['end'])
                
            elif 'timeslots[]' in data:
                timeslots = post_data.getlist('timeslots[]')
                for slot in timeslots:
                    poll.time_slots.get(pk=slot).delete()
                
            else:
                for field, value in data.items():
                    setattr(poll, field, value)
                    poll.save()
                    if field == 'notify':
                        notify_guests_with_changes.delay(poll.pk, 're-opened')                

              
        return redirect(success_url, {'poll': poll})
    

class PollDelete(LoginRequiredMixin, DeleteView):
    model = Poll
    success_url = reverse_lazy('polls:my_polls')
    uuid_url_kwarg = 'guid'

    def get_object(self):
        return self.get_queryset().get(guid=self.kwargs[self.uuid_url_kwarg])

    def get(self, request, *args, **kwargs):
        poll_url = reverse_lazy('polls:poll_detail', kwargs={'guid': self.kwargs[self.uuid_url_kwarg]})
        return redirect(poll_url)
    

@login_required
@require_http_methods(['POST'])
def invite(request, guid):
    guests = request.POST.getlist('guest_list[]')

    invite_guests.delay(guid, guests, request.get_host())
    
    return redirect(reverse_lazy('polls:poll_detail', kwargs={'guid': guid}))


@require_http_methods(['POST'])
def add_guest(request, guid=None):
    guest_name = request.POST.get('name')
    guest_email = request.POST.get('email')
    guest_email = guest_email if guest_email else None
    poll = Poll.objects.get(guid=guid)

    try:
        guest = poll.guests.create(name=guest_name, email=guest_email)
        params = {'gid': guest.guid}
        query_string = urlencode(params)
        return redirect(reverse_lazy('polls:poll_detail' , kwargs={'guid': guid}) + 
            '?' + query_string)
    except:
        params = {'invite': poll.token}
        query_string = urlencode(params)
        messages.error(request, 'Name or Email is already exist for another guest')
        return redirect(reverse_lazy('polls:poll_detail' , kwargs={'guid': guid}) + 
            '?' + query_string)
        

@require_http_methods(['GET'])
def get_guest(request, poll_guid=None, guest_guid=None):
    try:
        poll = Poll.objects.get(guid=poll_guid)
        instance = Guest.objects.prefetch_related('votes').get(guid=guest_guid, poll=poll)
        guest = serializers.serialize('json', [instance])
        votes = serializers.serialize('json', instance.votes.all())
        return JsonResponse({'guest': guest, 'votes': votes})
    except:
        return JsonResponse({})
    

@require_http_methods(['POST'])
def edit_guest_name(request, guid=None):
    new_name = request.POST.get('name')
    guest = Guest.objects.select_related('poll').get(guid=guid)

    try:
        guest.name = new_name
        guest.save()
    except:
        messages.error(request, 'This name belongs to another guest. Please, choose a valid name')
    finally:
        params = {'gid': guid}
        query_string = urlencode(params)
        return redirect(reverse_lazy('polls:poll_detail' , kwargs={'guid': guest.poll.guid}) + 
        '?' + query_string)


@require_http_methods(['POST'])
def contact(request):
    data = request.POST
    send_contact_message.delay(data)
    return JsonResponse({'status': 'ok'})

templates/polls/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}<title>Poll4Dates</title>{% endblock title %}

{% block content %}
<section id="hero">
    <div class="hero-container" data-aos="fade-in">
        <h1>Welcome to poll4dates</h1>
        <h2>Connect anywhere around the globe. Coordinate across timezones with Poll4Dates.</h2>
        <img src="{% static 'polls/img/hero-img.png' %}" alt="Hero Imgs" data-aos="zoom-out" data-aos-delay="100">
        <a href="{% url 'polls:plan' %}" class="btn-get-started scrollto">Plan Event</a>
    </div>
</section>

<main id="main">
    <section id="get-started" class="padd-section text-center">
        <div class="container" data-aos="fade-up">
            <div class="section-title text-center">
                <h2>Let us show you how</h2>
                <p class="separator">Simply create a poll with any number of date and time options for your event.
                    Then send the poll to your guests either by sharing the general link to the poll or by having
                    Poll4Dates send them an email invitation to vote in the poll. That’s it! You can watch the
                    votes come in real-time as your guests enter their preferences. When ready, pick the best
                    date/time for the event directly from the poll. Check out our Help Center for more details.
                </p>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-4" data-aos="zoom-in" data-aos-delay="100">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/one.svg' %}" alt="img">
                        <p style="font-size:20px">
                            Select date/time options for your event and share with your friends.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4" data-aos="zoom-in" data-aos-delay="200">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/two.svg' %}" alt="img">
                        <p style="font-size:20px">
                            Without having to log in, your friends can mark their availability for
                            the proposed dates.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4" data-aos="zoom-in" data-aos-delay="300">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/three.svg' %}" alt="img">
                        <p style="font-size:20px">Schedule your event on the date that works for everyone!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section id="features" class="padd-section text-center">
        <div class="container" data-aos="fade-up">
            <div class="section-title text-center">
                <h2>Use Cases</h2>
            </div>

            <div class="row" data-aos="fade-up" data-aos-delay="100">
                <div class="col-md-6 col-lg-4">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/family.svg' %}" alt="img">
                        <h4>Family Reunion</h4>
                        <p>Time to plan the summer family reunion and bring everyone together! Get in touch with
                            uncle Webb and cousin Sabby to pick a date before calendars fill up.</p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/basketball.svg' %}" alt="img">
                        <h4>Pickup Basketball</h4>
                        <p>Ready to shoot some hoops? Use Poll4Dates to find a time to head outdoors for a match with
                            friends.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/meeting.svg' %}" alt="img">
                        <h4>Board Meeting</h4>
                        <p>Is it hard to find a time when board members can attend a meeting? Poll4Dates is the
                            perfect tool to schedule meetings without back-and-forth email hassle.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/book.svg' %}" alt="img">
                        <h4>Book Club</h4>
                        <p>Scheduling a book club meeting can mean a million email chains. Simply survey your book
                            club members to see when they are available.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/bbq.svg' %}" alt="img">
                        <h4>Weekend BBQ</h4>
                        <p>Get friends together for a weekend BBQ in the park or at your house. Find what day works
                            best without lengthy email chains.
                        </p>
                    </div>
                </div>

                <div class="col-md-6 col-lg-4">
                    <div class="feature-block">
                        <img src="{% static 'polls/img/svg/golf.svg' %}" alt="img">
                        <h4>Round of Golf</h4>
                        <p>Meet and play golf with friends. Investing time in what brings you joy is worth it!
                            Quickly find the time that works for everyone with Poll4Dates.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section id="testimonials" class="padd-section text-center">
        <div class="container" data-aos="fade-up">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="testimonials-content">
                        <div id="carousel-example-generic" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item  active">
                                    <div class="top-top">
                                        <h2>Our Users Speack volumes us</h2>
                                        <p>I run an informal tennis club where I need a really good polling program
                                            in order to arrange matches for my 40-odd,
                                            not-very-technologically-savvy, members. I was delighted to discover
                                            Poll4Dates. In its simplicity of use and its quality of output it
                                            surpasses by a long chalk what I had used before. It is an outstanding
                                            piece of software which I heartily recommend to anyone who has to try to
                                            organise events for a club, society or similar grouping.
                                        </p>
                                        <h4>Nicholas<span>London, UK</span></h4>
                                    </div>
                                </div>

                                <div class="carousel-item ">
                                    <div class="top-top">
                                        <h2>Our Users Speack volumes us</h2>
                                        <p>Poll4Dates is a quick and easy way to find my friend’s availability
                                            for both small and large events. It’s super user-friendly and makes
                                            identifying the winning date really simple. I recommend Poll4Dates to
                                            anyone looking to minimize discussions back and forth and maximize the
                                            number of people at the party!
                                        </p>
                                        <h4>Sonja<span>Reykjavík, Iceland</span></h4>
                                    </div>
                                </div>

                                <div class="carousel-item ">
                                    <div class="top-top">
                                        <h2>Our Users Speack volumes us</h2>
                                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting
                                            industry. Lorem Ipsum has been the industry's standard dummy text ever
                                            since the 1500s, when an unknown printer took a galley of type and
                                            scrambled it to make a type
                                            specimen book. It has survived not only five centuries.
                                        </p>
                                        <h4>David Spark<span>manager</span></h4>
                                    </div>
                                </div>
                            </div>

                            <div class="btm-btm">
                                <ul class="list-unstyled carousel-indicators">
                                    <li data-bs-target="#carousel-example-generic" data-bs-slide-to="0" class="active"></li>
                                    <li data-bs-target="#carousel-example-generic" data-bs-slide-to="1"></li>
                                    <li data-bs-target="#carousel-example-generic" data-bs-slide-to="2"></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="contact" class="padd-section">
        <div class="container" data-aos="fade-up">
            <div class="section-title text-center">
                <h2>Contact</h2>
            </div>

            <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="100">
                <div class="col-lg-3 col-md-4">
                    <div class="info">
                        <div>
                            <i class="bi bi-geo-alt"></i>
                            <p>A108 Adam Street<br>New York, NY 535022</p>
                        </div>

                        <div class="email">
                            <i class="bi bi-envelope"></i>
                            <p>info@example.com</p>
                        </div>

                        <div>
                            <i class="bi bi-phone"></i>
                            <p>+1 5589 55488 55s</p>
                        </div>
                    </div>

                    <div class="social-links">
                        <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                        <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                        <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                        <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
                    </div>
                </div>

                <div class="col-lg-5 col-md-8">
                    <div class="form">
                        <form action="{% url 'polls:contact' %}" method="post" role="form" class="php-email-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name"
                                    required>
                            </div>

                            <div class="form-group mt-3">
                                <input type="email" class="form-control" name="email" id="email"
                                    placeholder="Your Email" required>
                            </div>

                            <div class="form-group mt-3">
                                <input type="text" class="form-control" name="subject" id="subject"
                                    placeholder="Subject" required>
                            </div>

                            <div class="form-group mt-3">
                                <textarea class="form-control" name="message" rows="5" placeholder="Message"
                                    required>
                                </textarea>
                            </div>

                            <div class="my-3">
                                <div class="loading">Loading</div>
                                <div class="error-message"></div>
                                <div class="sent-message">
                                    Your message sent successfully
                                </div>
                            </div>

                            <div class="text-center">
                                <button type="submit">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

templates/polls/list.html
{% extends 'base.html' %}
{% block title %} <title>My Polls</title>{% endblock %}
{% load static %}
{% block content %}
<main>
    <section class="inner-page pt-4 mt-5">
        <div class="container col-md-12 mt-5">
            {% for poll in polls %}
                <div class="shadow mb-5 bg-white rounded row col-md-6 mx-auto p-0">
                    <div class="p-3">
                        <h4>{{poll.event_name}}</h4>
                        <p>Organized by: {{poll.event_organizer}}</p>
                        <p><i class="bi bi-geo-alt-fill" style="color: #71c55d"></i> {{poll.event_location}}</p>
                        <p><i class="bi bi-circle-fill" style="color: {% if poll.ended %} #696969	 
                            {% else %} #71c55d {% endif %}"></i> RSVP by: {{poll.rsvp_by}}</p>
                    </div>

                    <div style="background-color: #71c55d;" class="rounded p-3 text-center">
                        <a href="{% url 'polls:poll_detail' poll.guid %}"
                            style="color: white; font-weight: bold; text-decoration: none;">
                            View Poll
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}