poll4dates/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("polls.urls"))
]

polls/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'polls'

urlpatterns = [
    path("", TemplateView.as_view(template_name='polls/index.html'), name='index'),
    path("plan/", views.PollCreate.as_view(), name='plan'),
    path("polls/", views.PollList.as_view(), name='my_polls'),
    path("polls/<uuid:guid>/", views.PollDetail.as_view(), name='poll_detail'),
    path("polls/<uuid:guid>/edit/", views.PollUpdate.as_view(), name='poll_update'),
    path("polls/<uuid:guid>/delete/", views.PollDelete.as_view(), name='delete'),
    path("polls/<uuid:guid>/invite/", views.invite, name='invite'),
    path("polls/<uuid:guid>/guests/", views.add_guest, name='add_guest'),
    path("polls/<uuid:poll_guid>/guests/<uuid:guest_guid>/", views.get_guest, name='get_guest'),
    path("guests/<uuid:guid>/edit/", views.edit_guest_name, name="edit_guest_name"),
    path("contact/", views.contact, name='contact')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    {% block title %}{% endblock %}
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Roboto:100,300,400,500,700|Philosopher:400,400i,700,700i"
        rel="stylesheet">
    <link href="{% static 'polls/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'polls/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'polls/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'polls/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'polls/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <link href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap-grid.css' rel='stylesheet'>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css' rel='stylesheet'>
    <link href="{% static 'polls/css/style.css' %}" rel="stylesheet">
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="50">
    <header id="header" class="header fixed-top d-flex align-items-center shadow">
        <div class="container d-flex align-items-center justify-content-between">
            <div id="logo">
                <h1><a href="{% url 'polls:index' %}">Poll<span>4</span>Dates</a></h1>
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="{% url 'polls:index' %}">Home</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'polls:index' %}#get-started">How To</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'polls:index' %}#features">Use Cases</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'polls:index' %}#testimonials">Testimonials</a></li>
                    <li><a class="nav-link scrollto" href="{% url 'polls:index' %}#contact">Contact</a></li>
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#"><span>{{user.name}}</span> <i class="bi bi-chevron-down"></i></a>
                        <ul>
                            <li><a class="nav-link scorllto" href="{% url 'polls:my_polls' %}">My Polls</a></li>
                            <li>
                                <form method="post" action="{% url 'account_logout' %}" style="margin-left: 13px">
                                    {% csrf_token %}
                                    <input type="hidden" name="next" value="{{ request.get_full_path }}"/>
                                    <button style="border: none; background-color: white;">
                                        <i class="bi bi-box-arrow-right ml-0" style="margin-right: 5px;"></i>
                                        Sign out
                                    </button>
                                </form>
                            </li>
                        </ul>
                    </li>
                    {% else %}
                    <li>
                        <a class="nav-link scrollto" href="{% url 'account_login' %}">
                            <button style="border: none; background-color: white;">
                                <i class="bi bi-box-arrow-in-right ml-0" style="margin-right: 5px;"></i>
                                Sign In
                            </button>
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav>
        </div>
    </header>

    {% block content%}

    {% endblock %}

    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-lg-4">
                    <div class="footer-logo">
                        <a class="navbar-brand" href="#">Poll4Dates</a>
                    </div>
                </div>

                <div class="col-sm-6 col-md-3 col-lg-2">
                    <div class="list-menu">
                        <h4>Abou Us</h4>
                        <ul class="list-unstyled">
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Features item</a></li>
                            <li><a href="#">Live streaming</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>

                    </div>
                </div>

                <div class="col-sm-6 col-md-3 col-lg-2">
                    <div class="list-menu">
                        <h4>Abou Us</h4>
                        <ul class="list-unstyled">
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Features item</a></li>
                            <li><a href="#">Live streaming</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-sm-6 col-md-3 col-lg-2">
                    <div class="list-menu">
                        <h4>Support</h4>
                        <ul class="list-unstyled">
                            <li><a href="#">faq</a></li>
                            <li><a href="#">Editor help</a></li>
                            <li><a href="#">Contact us</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>

                <div class="col-sm-6 col-md-3 col-lg-2">
                    <div class="list-menu">
                        <h4>Abou Us</h4>
                        <ul class="list-unstyled">
                            <li><a href="#">About us</a></li>
                            <li><a href="#">Features item</a></li>
                            <li><a href="#">Live streaming</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="copyrights">
            <div class="container">
                <p>&copy; Copyrights Poll4Dates. All rights reserved.</p>
                <div class="credits"> Designed by 
                    <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
            </div>
        </div>

    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
            class="bi bi-arrow-up-short"></i></a>

    <script src="{% static 'polls/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'polls/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'polls/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'polls/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'polls/vendor/php-email-form/validate.js' %}"></script>
    <script src="{% static 'fullcalendar/dist/index.global.js' %}"></script>

    <script src="{% static 'polls/js/main.js' %}"></script>
    {% block extrascripts %}
    {% endblock %}
</body>

</html>